package Juego;

/**
 *
 * @author keneth
 */

public class Cambio_Turno1 extends javax.swing.JPanel {

    Almacen_Nombres Almacen_Nombres = new Almacen_Nombres();

    public Cambio_Turno1() {
        initComponents();
        actualizarNombre1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Nombre1 = new javax.swing.JLabel();
        Txt_Accion = new javax.swing.JLabel();
        Confirmar_Btn = new javax.swing.JPanel();
        Confirmar_Txt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_Nombre1.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        add(Txt_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 690, 70));

        Txt_Accion.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Txt_Accion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Accion.setText("Presione para continuar.");
        add(Txt_Accion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 690, 70));

        Confirmar_Btn.setBackground(new java.awt.Color(0, 0, 0));

        Confirmar_Txt.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        Confirmar_Txt.setForeground(new java.awt.Color(255, 255, 255));
        Confirmar_Txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Confirmar_Txt.setText("CONFIRMAR");
        Confirmar_Txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confirmar_Txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Confirmar_TxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Confirmar_BtnLayout = new javax.swing.GroupLayout(Confirmar_Btn);
        Confirmar_Btn.setLayout(Confirmar_BtnLayout);
        Confirmar_BtnLayout.setHorizontalGroup(
            Confirmar_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Confirmar_BtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Confirmar_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Confirmar_BtnLayout.setVerticalGroup(
            Confirmar_BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Confirmar_BtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Confirmar_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(Confirmar_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void Confirmar_TxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Confirmar_TxtMouseClicked
        Jugador_2 Jugador_2 = new Jugador_2();
        Panel_Principal.ShowPanel(Jugador_2);
    }//GEN-LAST:event_Confirmar_TxtMouseClicked

    public void actualizarNombre1() {
        String nombre1 = Almacen_Nombres.getNombreJugador2();
        Txt_Nombre1.setText("Turno de: " + nombre1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Confirmar_Btn;
    private javax.swing.JLabel Confirmar_Txt;
    private javax.swing.JLabel Txt_Accion;
    private javax.swing.JLabel Txt_Nombre1;
    // End of variables declaration//GEN-END:variables
}
