package Juego;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author keneth
 */

public class Ingreso_Nombres extends javax.swing.JPanel {

    public Ingreso_Nombres() {
        initComponents();
        Nom_1.setFocusable(false);
        Nom_2.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Img_Portada = new javax.swing.JLabel();
        Img_Logo = new javax.swing.JLabel();
        Txt_Iniciar_Juego = new javax.swing.JLabel();
        Txt_Jugador_1 = new javax.swing.JLabel();
        Nom_1 = new javax.swing.JTextField();
        Linea_1 = new javax.swing.JSeparator();
        Txt_Jugador_2 = new javax.swing.JLabel();
        Nom_2 = new javax.swing.JTextField();
        Linea_2 = new javax.swing.JSeparator();
        Panel_Entrar = new javax.swing.JPanel();
        Boton_Entrar = new javax.swing.JLabel();
        Panel_Salir = new javax.swing.JPanel();
        Boton_Salir = new javax.swing.JLabel();
        Mensaje_Error = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Img_Portada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Portada.jpg"))); // NOI18N
        Img_Portada.setText("jLabel3");
        add(Img_Portada, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 500));

        Img_Logo.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        Img_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoaPortadaBattleShip.jpeg"))); // NOI18N
        Img_Logo.setText("Battleship");
        add(Img_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Txt_Iniciar_Juego.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        Txt_Iniciar_Juego.setText("INICIAR JUEGO");
        add(Txt_Iniciar_Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        Txt_Jugador_1.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        Txt_Jugador_1.setText("JUGADOR 1");
        add(Txt_Jugador_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 30));

        Nom_1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Nom_1.setForeground(new java.awt.Color(153, 153, 153));
        Nom_1.setText("Por favor. Ingrese su nombre");
        Nom_1.setBorder(null);
        Nom_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Nom_1MousePressed(evt);
            }
        });
        add(Nom_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 330, 20));

        Linea_1.setBackground(new java.awt.Color(0, 0, 0));
        Linea_1.setForeground(new java.awt.Color(0, 0, 0));
        add(Linea_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 330, 10));

        Txt_Jugador_2.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        Txt_Jugador_2.setText("JUGADOR 2");
        add(Txt_Jugador_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, 30));

        Nom_2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Nom_2.setForeground(new java.awt.Color(153, 153, 153));
        Nom_2.setText("Por favor. Ingrese su nombre");
        Nom_2.setBorder(null);
        Nom_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Nom_2MousePressed(evt);
            }
        });
        add(Nom_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 330, 20));

        Linea_2.setBackground(new java.awt.Color(0, 0, 0));
        Linea_2.setForeground(new java.awt.Color(0, 0, 0));
        add(Linea_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 330, 10));

        Panel_Entrar.setBackground(new java.awt.Color(0, 0, 0));

        Boton_Entrar.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        Boton_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_Entrar.setText("ENTRAR");
        Boton_Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_EntrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_EntrarLayout = new javax.swing.GroupLayout(Panel_Entrar);
        Panel_Entrar.setLayout(Panel_EntrarLayout);
        Panel_EntrarLayout.setHorizontalGroup(
            Panel_EntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Panel_EntrarLayout.setVerticalGroup(
            Panel_EntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_Entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(Panel_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 100, 40));

        Panel_Salir.setBackground(new java.awt.Color(0, 0, 0));

        Boton_Salir.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        Boton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Boton_Salir.setText("SALIR");
        Boton_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_SalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_SalirLayout = new javax.swing.GroupLayout(Panel_Salir);
        Panel_Salir.setLayout(Panel_SalirLayout);
        Panel_SalirLayout.setHorizontalGroup(
            Panel_SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        Panel_SalirLayout.setVerticalGroup(
            Panel_SalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boton_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(Panel_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 100, 40));

        Mensaje_Error.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Mensaje_Error.setForeground(new java.awt.Color(255, 0, 0));
        Mensaje_Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Mensaje_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 330, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_EntrarMouseClicked
        String Nombre_Usuario_1 = Nom_1.getText();
        String Nombre_Usuario_2 = Nom_2.getText();

        String Error_Nombres_Usuarios = Validar_Nombres_Usuarios(Nombre_Usuario_1, Nombre_Usuario_2);
        Almacen_Nombres Almacen_Nombres = new Almacen_Nombres();
        Almacen_Nombres.setNombres(Nombre_Usuario_1, Nombre_Usuario_2);

        if (Error_Nombres_Usuarios != null) {
            // Mostrar mensaje de error en el panel
            Mensaje_Error.setText(Error_Nombres_Usuarios);
            Mensaje_Error.setVisible(true);
            // Crear un temporizador para ocultar el mensaje después de un segundo
            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Mensaje_Error.setVisible(false);
                }
            });
            timer.setRepeats(false);
            timer.start();
        } else {
            Jugador_1 Jugador_1 = new Jugador_1();
            Panel_Principal.ShowPanel(Jugador_1);
        }
    }//GEN-LAST:event_Boton_EntrarMouseClicked


    private void Boton_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Boton_SalirMouseClicked

    private void Nom_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nom_1MousePressed
        if (Nom_1.getText().equals("Por favor. Ingrese su nombre")) {
            Nom_1.setFocusable(true);
            Nom_1.requestFocusInWindow();
            Nom_1.setText("");
            Nom_1.setForeground(Color.black);
        }
        if (Nom_2.getText().isEmpty()) {
            Nom_2.setFocusable(false);
            Nom_2.setText("Por favor. Ingrese su nombre");
            Nom_2.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Nom_1MousePressed

    private void Nom_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nom_2MousePressed
        if (Nom_2.getText().equals("Por favor. Ingrese su nombre")) {
            Nom_2.setFocusable(true);
            Nom_2.requestFocusInWindow();
            Nom_2.setText("");
            Nom_2.setForeground(Color.black);
        }
        if (Nom_1.getText().isEmpty()) {
            Nom_1.setFocusable(false);
            Nom_1.setText("Por favor. Ingrese su nombre");
            Nom_1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Nom_2MousePressed

    private String Validar_Nombres_Usuarios(String NombreUsuario1, String NombreUsuario2) {
        if (NombreUsuario1.isEmpty() || NombreUsuario2.isEmpty()
                || NombreUsuario1.equals("Por favor. Ingrese su nombre")
                || NombreUsuario2.equals("Por favor. Ingrese su nombre")) {
            return "El campo está vacío.";
        } else if (NombreUsuario1.length() < 2 || NombreUsuario2.length() < 2) {
            return "Mínimo 2 caracteres.";
        } else if (NombreUsuario1.length() > 11 || NombreUsuario2.length() > 11) {
            return "Máximo 11 caracteres.";
        } else if (NombreUsuario1.equals(NombreUsuario2)) {
            return "Los nombres de usuario son iguales.";
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton_Entrar;
    private javax.swing.JLabel Boton_Salir;
    private javax.swing.JLabel Img_Logo;
    private javax.swing.JLabel Img_Portada;
    private javax.swing.JSeparator Linea_1;
    private javax.swing.JSeparator Linea_2;
    private javax.swing.JLabel Mensaje_Error;
    private javax.swing.JTextField Nom_1;
    private javax.swing.JTextField Nom_2;
    private javax.swing.JPanel Panel_Entrar;
    private javax.swing.JPanel Panel_Salir;
    private javax.swing.JLabel Txt_Iniciar_Juego;
    private javax.swing.JLabel Txt_Jugador_1;
    private javax.swing.JLabel Txt_Jugador_2;
    // End of variables declaration//GEN-END:variables
}
