package Juego;

/**
 *
 * @author keneth
 */

public class Mostrar_Ganador extends javax.swing.JPanel {

    Almacen_Nombres Almacen_Nombres = new Almacen_Nombres();
    public static Mostrar_Ganador instancia;

    public Mostrar_Ganador() {
        initComponents();
        actualizarNombres();
        instancia = this;
        Txt_Ganador1.setVisible(false);
        Txt_Ganador2.setVisible(false);

        MATRIZ1.setText(imprimir1());
        MATRIZ2.setText(imprimir2());
    }

    public void actualizarNombres() {
        String nombre1 = Almacen_Nombres.getNombreJugador1();
        String nombre2 = Almacen_Nombres.getNombreJugador2();
        Txt_Nombre1.setText(nombre1);
        Txt_Nombre2.setText(nombre2);
    }

    public String imprimir1() {
        StringBuilder sb = new StringBuilder();
        sb.append("  ");
        for (int i = 1; i <= 9; i++) {
            sb.append(i + " ");
        }
        sb.append("\n");
        for (int i = 1; i <= 9; i++) {
            sb.append((char) ('A' + i - 1) + " ");
            for (int j = 1; j <= 9; j++) {
                if (Jugador_1.Barcos_EnTablero1[j][i]) {
                    sb.append("X ");
                } else {
                    sb.append("- ");
                }
            }
            if (i < 9) {
                sb.append("\n");
            }
        }
        return sb.toString();
    }

    public String imprimir2() {
        StringBuilder sb = new StringBuilder();
        sb.append("  ");
        for (int i = 1; i <= 9; i++) {
            sb.append(i + " ");
        }
        sb.append("\n");
        for (int i = 1; i <= 9; i++) {
            sb.append((char) ('A' + i - 1) + " ");
            for (int j = 1; j <= 9; j++) {
                if (Jugador_2.Barcos_EnTablero2[j][i]) {
                    sb.append("X ");
                } else {
                    sb.append("- ");
                }
            }
            if (i < 9) {
                sb.append("\n");
            }
        }
        return sb.toString();
    }

    public boolean jugador1Gana;
    public boolean jugador2Gana;

    public void setJugador1Gana(boolean gana) {
        jugador1Gana = gana;
        Txt_Ganador1.setVisible(true);
    }

    public void setJugador2Gana(boolean gana) {
        jugador2Gana = gana;
        Txt_Ganador2.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Nombre1 = new javax.swing.JLabel();
        Txt_Nombre2 = new javax.swing.JLabel();
        Img_Capitan1 = new javax.swing.JLabel();
        Img_Capitan2 = new javax.swing.JLabel();
        Txt_Ganador1 = new javax.swing.JLabel();
        Txt_Ganador2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MATRIZ2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        MATRIZ1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_Nombre1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        Txt_Nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Nombre1.setText("JUGADOR1");
        add(Txt_Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 25, 160, 45));

        Txt_Nombre2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        Txt_Nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Nombre2.setText("JUGADOR 2");
        add(Txt_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 25, 160, 45));

        Img_Capitan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Capitan1.png"))); // NOI18N
        Img_Capitan1.setText("jLabel1");
        add(Img_Capitan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 160, 200));

        Img_Capitan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Capitan2.png"))); // NOI18N
        Img_Capitan2.setText("jLabel2");
        add(Img_Capitan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 160, 200));

        Txt_Ganador1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Txt_Ganador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Ganador1.setText("GANADOR");
        Txt_Ganador1.setFocusable(false);
        add(Txt_Ganador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 160, 30));

        Txt_Ganador2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        Txt_Ganador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txt_Ganador2.setText("GANADOR");
        Txt_Ganador2.setFocusable(false);
        add(Txt_Ganador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 160, 30));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jScrollPane2.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setWheelScrollingEnabled(false);

        MATRIZ2.setBorder(null);
        MATRIZ2.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        MATRIZ2.setFocusable(false);
        MATRIZ2.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(MATRIZ2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 160, 160));

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setFocusable(false);
        jScrollPane4.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jScrollPane4.setVerifyInputWhenFocusTarget(false);
        jScrollPane4.setWheelScrollingEnabled(false);

        MATRIZ1.setBorder(null);
        MATRIZ1.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        MATRIZ1.setAutoscrolls(false);
        MATRIZ1.setFocusable(false);
        MATRIZ1.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(MATRIZ1);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 160));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Img_Capitan1;
    private javax.swing.JLabel Img_Capitan2;
    private javax.swing.JTextPane MATRIZ1;
    private javax.swing.JTextPane MATRIZ2;
    private javax.swing.JLabel Txt_Ganador1;
    private javax.swing.JLabel Txt_Ganador2;
    private javax.swing.JLabel Txt_Nombre1;
    private javax.swing.JLabel Txt_Nombre2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
